"""
Markdown Digest Writer
Generates Obsidian-compatible Markdown files from the content digest.
"""

import os
from datetime import datetime
from typing import Dict, List


def generate_markdown_digest(triaged_articles: Dict[str, list], output_dir: str = "output/digests") -> str:
    """
    Generate an Obsidian-compatible Markdown digest file.
    
    Args:
        triaged_articles: Dictionary with 'b2c', 'b2b' article lists
        output_dir: Directory to save the markdown file
        
    Returns:
        Path to the generated markdown file
    """
    today = datetime.now()
    date_str = today.strftime('%Y-%m-%d')
    date_display = today.strftime('%B %d, %Y')
    
    b2c_articles = [a for a in triaged_articles.get('b2c', []) if a.get('generated_content')]
    b2b_articles = [a for a in triaged_articles.get('b2b', []) if a.get('generated_content')]
    
    # Build markdown content
    lines = []
    
    # Frontmatter for Obsidian
    lines.append("---")
    lines.append(f"date: {date_str}")
    lines.append(f"type: medical-digest")
    lines.append(f"b2c_count: {len(b2c_articles)}")
    lines.append(f"b2b_count: {len(b2b_articles)}")
    lines.append("---")
    lines.append("")
    
    # Header
    lines.append(f"# 🏥 Medical Insights — {date_display}")
    lines.append("")
    lines.append(f"> **{len(b2c_articles)}** articles for patients & public | **{len(b2b_articles)}** clinical editorials for colleagues")
    lines.append("")
    lines.append("---")
    lines.append("")
    
    # B2C Section
    if b2c_articles:
        lines.append("## 📢 For Patients & Public")
        lines.append("")
        
        for article in b2c_articles:
            lines.append(f"### {article.get('title', 'Untitled')}")
            lines.append("")
            lines.append(f"*{article.get('journal', '')} | {article.get('pub_date', '')}*")
            if article.get('url'):
                lines.append(f"[Read Original]({article.get('url')})")
            lines.append("")
            lines.append(article.get('generated_content', ''))
            lines.append("")
            lines.append("---")
            lines.append("")
    
    # B2B Section
    if b2b_articles:
        lines.append("## 👨‍⚕️ For Colleagues")
        lines.append("")
        
        for article in b2b_articles:
            lines.append(f"### {article.get('title', 'Untitled')}")
            lines.append("")
            lines.append(f"*{article.get('journal', '')} | {article.get('pub_date', '')}*")
            if article.get('url'):
                lines.append(f"[Read Original]({article.get('url')})")
            lines.append("")
            lines.append(article.get('generated_content', ''))
            lines.append("")
            lines.append("---")
            lines.append("")
    
    # Empty state
    if not b2c_articles and not b2b_articles:
        lines.append("*No articles generated today. Check back tomorrow!*")
        lines.append("")
    
    # Footer
    lines.append("---")
    lines.append(f"*Generated by Medical Content Engine | {today.strftime('%H:%M')}*")
    
    # Write file
    os.makedirs(output_dir, exist_ok=True)
    filename = f"{date_str}-medical-digest.md"
    filepath = os.path.join(output_dir, filename)
    
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    
    return filepath


def save_markdown_digest(triaged_articles: Dict[str, list], output_dir: str = "output/digests") -> str:
    """
    Save the digest and print status.
    
    Args:
        triaged_articles: Dictionary with 'b2c', 'b2b' article lists
        output_dir: Directory to save the markdown file
        
    Returns:
        Path to the generated file
    """
    print(f"\n📝 Generating Markdown digest...")
    print("-" * 40)
    
    filepath = generate_markdown_digest(triaged_articles, output_dir)
    
    print(f"  ✓ Saved: {filepath}")
    print("-" * 40)
    
    return filepath


if __name__ == "__main__":
    # Test with sample data
    test_articles = {
        'b2c': [{
            'title': 'Mediterranean Diet Reduces Heart Disease Risk by 30%',
            'journal': 'NEJM',
            'pub_date': '2024-12-20',
            'url': 'https://example.com/article1',
            'generated_content': '''The evidence continues to mount for the Mediterranean diet. In this week's New England Journal of Medicine, researchers present compelling data from a randomized trial of 7,500 adults.

The study found that those following a Mediterranean diet rich in olive oil, nuts, and fish had a 30% reduction in major cardiovascular events compared to a control diet (HR 0.70, 95% CI 0.58-0.85).

What makes this particularly noteworthy is the consistency with prior trials like PREDIMED, while addressing some of the methodological concerns raised about that earlier work.

The practical takeaway? The Mediterranean pattern isn't just about individual foods—it's about the synergy of the entire dietary pattern.'''
        }],
        'b2b': [{
            'title': 'FFR-Guided PCI Shows Sustained Benefit at 5 Years',
            'journal': 'JACC Cardiovascular Interventions',
            'pub_date': '2024-12-20',
            'url': 'https://example.com/article2',
            'generated_content': '''**Clinical Question**: Does FFR-guided PCI maintain superiority over angiography-guided PCI in intermediate lesions at 5 years?

**Trial Design**: Multicenter RCT, N=1,200 with intermediate stenosis (40-70%), 1:1 randomization to FFR-guided (n=600) vs angio-guided (n=600). Primary endpoint: MACE at 5 years.

**Results**: MACE 12.3% vs 18.1% (HR 0.66, 95% CI 0.52-0.84, p=0.003). TLR 5.2% vs 9.8% (p<0.001). NNT = 17 to prevent one MACE event.

**What I'm Taking to the Cath Lab**: The durability of FFR guidance is now confirmed. For intermediate lesions, the physiologic approach wins—and the benefit doesn't attenuate over time.

**Bottom Line**: FFR guidance prevents 1 MACE per 17 patients treated at 5 years. This should be standard of care for intermediate lesions.'''
        }]
    }
    
    filepath = save_markdown_digest(test_articles, "output/digests")
    print(f"\nTest file created: {filepath}")
